users:
  shubham:
    displayname: "Shubham Maurya"
    # password: "$argon2id$v=19$m=65536,t=3,p=2$BpLnfgDsc2WD8F2q$o/vzA4myCqZZ36bUGsDY//8mKUYNZZaR0t4MFFSs+iM"
    password: $argon2id$v=19$m=65536,t=1,p=8$UkFuS3BUL1A0SFh6VlJCbQ$DjpEiuKMYD8OzfRVXboH0Bdx8QsAnp05j2Cdc+qco2U
    email: shubham.maurya@localhost
    groups:
      - admins
      - dev
