users:
  shubham:
    displayname: "Shubham Maurya"
    # password: "$argon2id$v=19$m=65536,t=3,p=2$BpLnfgDsc2WD8F2q$o/vzA4myCqZZ36bUGsDY//8mKUYNZZaR0t4MFFSs+iM"
    password: $argon2id$v=19$m=1024,t=1,p=8$YWFhYWFhYWFhYWFhYWFhYQ$9FGFho2lL5F480+xzYPmmfrMf9OHWJFmXOC9HOaVI8o
    email: shubham.maurya@localhost
    groups:
      - admins
      - dev
