global:
  checkNewVersion: true
  sendAnonymousUsage: false # true by default

################################################################
# Traefik Logging -  DEBUG, PANIC, FATAL, ERROR, WARN, and INFO (DEFAULT is ERROR)
################################################################
log:
  level: INFO
  format: common # common, json, logfmt
  # filePath: /var/log/traefik/traefik.log

accesslog:
  format: common # common, json, logfmt
  # filePath: /var/log/traefik/access.log

################################################################
# Entrypoint
################################################################
entryPoints:
  ping:
    address: ":8082"
  http:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: https

  https:
    # https
    address: ":443"
    http:
      middlewares:
        - securityHeaders@file
    # http:
    #   tls:
    #     certResolver: letsencrypt
    #     options: foobar
    #     certResolver: leresolver
    #     domains:
    #       - main: example.com
    #         sans:
    #           - foo.example.com
    #           - bar.example.com
    #       - main: test.com
    #         sans:
    #           - foo.test.com
    #           - bar.test.com

################################################################
# Challenege DNS
################################################################

# certificatesResolvers:
#   letsencrypt:
#     # https://docs.traefik.io/master/https/acme/#lets-encrypt
#     acme:
#       email: "shubhammaurya@grampower.com"
#       storage: /etc/traefik/acme/acme.json
#       # https://docs.traefik.io/master/https/acme/#httpchallenge
#       httpChallenge:
#         entryPoint: web

################################################################
# API and dashboard configuration
################################################################
api:
  dashboard: true # true by default
  insecure: false # Don't do this in production!

################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    network: proxy
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/dynamic.yml
    # directory: /etc/traefik
    watch: true
################################################################
# Enable traefik Pilot
################################################################
# pilot:
#   token: "17f55265-97cb-4dc2-b58e-2f82e0938b4f"
################################################################
# Enable Healthcheck
################################################################
ping:
  entryPoint: "ping"
